apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-ui-proxy
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-ui-proxy
  template:
    metadata:
      labels:
        app: spark-ui-proxy
    spec:
      serviceAccountName: spark-ui-proxy-sa
      containers:
      - name: proxy
        # 최신 공식 이미지로 교체
        image: "ghcr.io/kubeflow/spark-operator/spark-ui-proxy:v1beta2-1.4.1"
        imagePullPolicy: IfNotPresent
        args:
        - "-master"
        - "https://kubernetes.default.svc" # 클러스터 내부 API 주소
        - "-namespace"
        - "spark" # 감시할 네임스페이스
        - "-port"
        - "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui-proxy-svc
  namespace: spark
spec:
  selector:
    app: spark-ui-proxy
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ui-ingress
  namespace: spark
spec:
  ingressClassName: nginx
  rules:
  - host: spark-ui.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-ui-proxy-svc
            port:
              number: 80