apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-ui-proxy-sa
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-ui-proxy-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-ui-proxy-role-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: spark-ui-proxy-sa
    namespace: spark
roleRef:
  kind: Role
  name: spark-ui-proxy-role
  apiGroup: rbac.authorization.k8s.io