# spark-operator-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-spark-operator-role-binding
  namespace: spark  # 권한을 행사할 방
subjects:
  - kind: ServiceAccount
    name: my-spark-operator-controller
    namespace: spark-operator  # 오퍼레이터가 살고 있는 방
roleRef:
  kind: ClusterRole
  name: edit # 쿠버네티스 표준 관리자 권한 (파드 생성 등 가능)
  apiGroup: rbac.authorization.k8s.io